-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

-- WARNING : ALL TABLES WILL BE DROPPED.
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

-- TABLES

CREATE TABLE "public"."users"( 
	"id" int NOT NULL,
	"email" varchar(50) NOT NULL,
	"password" varchar(25) NOT NULL);

CREATE TABLE "public"."system_personels"( 
	"id" int NOT NULL,
	"user_id" int NOT NULL,
	"first_name" varchar(25) NOT NULL,
	"last_name" varchar(25) NOT NULL,
	"nationality_id" varchar(11) NOT NULL,
	"birth_of_date" date NOT NULL);

CREATE TABLE "public"."candidates"( 
	"id" int NOT NULL,
	"user_id" int NOT NULL,
	"first_name" varchar(25) NOT NULL,
	"last_name" varchar(25) NOT NULL,
	"nationality_id" varchar(11) NOT NULL,
	"birth_of_date" date NOT NULL);
	
CREATE TABLE "public"."employers"( 
	"id" int NOT NULL,
	"user_id" int NOT NULL,
	"company_name" varchar(250) NOT NULL,
	"web_address" varchar(50) NOT NULL,
	"phone_number" varchar(25) NOT NULL,
	"is_activated" boolean NOT NULL);	
	
	
CREATE TABLE "public"."job_titles"( 
	"id" int NOT NULL,
	"title" varchar(50) NOT NULL);	
	

CREATE TABLE "public"."activation_codes"( 
	"id" int NOT NULL,
	"activation_code" varchar(50) NOT NULL,
	"is_confirmed" boolean NOT NULL,
	"confirmed_date" date NOT NULL);

CREATE TABLE "public"."activation_code_to_candidates"( 
	"id" int NOT NULL,
	"candidate_id" int NOT NULL);

CREATE TABLE "public"."activation_code_to_employers"( 
	"id" int NOT NULL,
	"employer_id" int NOT NULL);

CREATE TABLE "public"."employer_activation_by_system_personels"( 
	"id" int NOT NULL,
	"employer_id" int NOT NULL,
	"confirmed_system_personel_id" int,
	"is_confirmed" boolean NOT NULL,
	"confirmed_date" date);



-- KEYS (AUTO INCREMENT)

CREATE SEQUENCE "public"."users_id_seq" 
    INCREMENT BY 1 START WITH 1 
    OWNED BY "public"."users"."id";
	
CREATE SEQUENCE "public"."system_personels_id_seq" 
    INCREMENT BY 1 START WITH 1 
    OWNED BY "public"."system_personels"."id";
	
CREATE SEQUENCE "public"."candidates_id_seq" 
    INCREMENT BY 1 START WITH 1 
    OWNED BY "public"."candidates"."id";
	
CREATE SEQUENCE "public"."employers_id_seq" 
    INCREMENT BY 1 START WITH 1 
    OWNED BY "public"."employers"."id";
	
	
CREATE SEQUENCE "public"."job_titles_id_seq" 
    INCREMENT BY 1 START WITH 1 
    OWNED BY "public"."job_titles"."id";
	
	
CREATE SEQUENCE "public"."activation_codes_id_seq" 
    INCREMENT BY 1 START WITH 1 
    OWNED BY "public"."activation_codes"."id";

CREATE SEQUENCE "public"."employer_activation_by_system_personels_id_seq" 
    INCREMENT BY 1 START WITH 1 
    OWNED BY "public"."employer_activation_by_system_personels"."id";



-- PRIMARY KEYS

ALTER TABLE "public"."users" 
    ADD CONSTRAINT "pk_users_id" 
    PRIMARY KEY ("id");

ALTER TABLE "public"."employers" 
    ADD CONSTRAINT "pk_employers_id" 
    PRIMARY KEY ("id");
	
ALTER TABLE "public"."candidates" 
    ADD CONSTRAINT "pk_candidate_id" 
    PRIMARY KEY ("id");

ALTER TABLE "public"."system_personels" 
    ADD CONSTRAINT "pk_system_personels_id" 
    PRIMARY KEY ("id");


ALTER TABLE "public"."job_titles" 
    ADD CONSTRAINT "pk_job_titles_id" 
    PRIMARY KEY ("id");
	

ALTER TABLE "public"."activation_code_to_candidates" 
    ADD CONSTRAINT "pk_activation_code_candidates" 
    PRIMARY KEY ("id");

ALTER TABLE "public"."activation_code_to_employers" 
    ADD CONSTRAINT "pk_activation_code_employers" 
    PRIMARY KEY ("id");

ALTER TABLE "public"."activation_codes" 
    ADD CONSTRAINT "pk_activation_codes" 
    PRIMARY KEY ("id");

ALTER TABLE "public"."employer_activation_by_system_personels" 
    ADD CONSTRAINT "pk_employeractivationsystempersonels_id" 
    PRIMARY KEY ("id");

-- UNIQUES

ALTER TABLE "public"."users" 
    ADD CONSTRAINT "uc_users_email" 
    UNIQUE ("email");

ALTER TABLE "public"."candidates" 
    ADD CONSTRAINT "uc_candidates_nationality_id" 
    UNIQUE ("nationality_id");
	


ALTER TABLE "public"."activation_codes" 
    ADD CONSTRAINT "uc_activation_codes" 
    UNIQUE ("activation_code");



ALTER TABLE "public"."job_titles" 
    ADD CONSTRAINT "uc_job_titles_title" 
    UNIQUE ("title");



ALTER TABLE "public"."activation_code_to_candidates" 
    ADD CONSTRAINT "fk_activation_code_candidates_candidates" 
    FOREIGN KEY ("candidate_id") 
    REFERENCES "public"."candidates" ( "id");

ALTER TABLE "public"."activation_code_to_employers" 
    ADD CONSTRAINT "fk_activation_code_employers_employers" 
    FOREIGN KEY ("employer_id") 
    REFERENCES "public"."employers" ( "id");

ALTER TABLE "public"."activation_codes" 
    ADD CONSTRAINT "fk_activation_codes_activation_code_candidates" 
    FOREIGN KEY ("id") 
    REFERENCES "public"."activation_code_to_candidates" ( "id");

ALTER TABLE "public"."activation_codes" 
    ADD CONSTRAINT "fk_activation_codes_activation_code_employers" 
    FOREIGN KEY ("id") 
    REFERENCES "public"."activation_code_to_employers" ( "id");

-- FOREIGN KEYS

ALTER TABLE "public"."candidates" 
    ADD CONSTRAINT "fk_candidates_users" 
    FOREIGN KEY ("user_id") 
    REFERENCES "public"."users" ( "id");

ALTER TABLE "public"."system_personels" 
    ADD CONSTRAINT "fk_system_personels_users" 
    FOREIGN KEY ("user_id") 
    REFERENCES "public"."users" ( "id");
	
ALTER TABLE "public"."employers" 
    ADD CONSTRAINT "fk_employers_users" 
    FOREIGN KEY ("user_id") 
    REFERENCES "public"."users" ( "id");


ALTER TABLE "public"."employer_activation_by_system_personels" 
    ADD CONSTRAINT "fk_employer_activation_system_personels_system_personels" 
    FOREIGN KEY ("confirmed_system_personel_id") 
    REFERENCES "public"."system_personels" ( "id");

ALTER TABLE "public"."employer_activation_by_system_personels" 
    ADD CONSTRAINT "fk_employer_activation_system_personels_employers" 
    FOREIGN KEY ("employer_id") 
    REFERENCES "public"."employers" ( "id");



ALTER TABLE "public"."activation_codes" ALTER COLUMN "id" SET DEFAULT nextval('"public"."activation_codes_id_seq"');

ALTER TABLE "public"."employer_activation_by_system_personels" ALTER COLUMN "id" SET DEFAULT nextval('"public"."employer_activation_by_system_personels_id_seq"');

ALTER TABLE "public"."employer_activation_by_system_personels" ALTER COLUMN "is_confirmed" SET DEFAULT false;

ALTER TABLE "public"."employers" ALTER COLUMN "is_activated" SET DEFAULT false;

ALTER TABLE "public"."job_titles" ALTER COLUMN "id" SET DEFAULT nextval('"public"."job_titles_id_seq"');

ALTER TABLE "public"."users" ALTER COLUMN "id" SET DEFAULT nextval('"public"."users_id_seq"');


INSERT INTO "public"."job_titles" (title) 
VALUES ('Software Developer'),('Software Architect'),('Database Analyzer');